# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from PyQt5.QtCore import QThread
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import Qt, QTimer, pyqtSignal, pyqtSlot
from PyQt5.QtGui import QPixmap, QPainter, QColor, QImage, QBrush, QIcon
from PyQt5.QtWidgets import QFileDialog, QMessageBox




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(898, 646)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.MainWidget = QtWidgets.QWidget(self.centralwidget)
        self.MainWidget.setObjectName("MainWidget")
        self.MainWidget.setStyleSheet("""
                                      color: #d2d3df;
                                      """)
        self.gridLayout_2 = QtWidgets.QGridLayout(self.MainWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.SideBarwidget = QtWidgets.QWidget(self.MainWidget)
        self.SideBarwidget.setMinimumSize(QtCore.QSize(250, 0))
        self.SideBarwidget.setMaximumSize(QtCore.QSize(250, 16777215))
        self.SideBarwidget.setAutoFillBackground(False)
        self.SideBarwidget.setStyleSheet("background-color: #2b2e41")
        self.SideBarwidget.setObjectName("SideBarwidget")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.SideBarwidget)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.sideMainwidget = QtWidgets.QWidget(self.SideBarwidget)
        self.sideMainwidget.setStyleSheet("text-align: center;")
        self.sideMainwidget.setObjectName("sideMainwidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.sideMainwidget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.MenuMainverticalLayout = QtWidgets.QVBoxLayout()
        self.MenuMainverticalLayout.setObjectName("MenuMainverticalLayout")
        self.Titlelabel_3 = QtWidgets.QLabel(self.sideMainwidget)
        self.Titlelabel_3.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Titlelabel_3.setStyleSheet("color: #d2d3df;\n"
"font-weight: bold;\n"
"font-size: 25px;")
        self.Titlelabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.Titlelabel_3.setObjectName("Titlelabel_3")
        self.MenuMainverticalLayout.addWidget(self.Titlelabel_3)
        self.MenuContentwidget = QtWidgets.QWidget(self.sideMainwidget)
        self.MenuContentwidget.setStyleSheet("text-align: center;")
        self.MenuContentwidget.setObjectName("MenuContentwidget")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.MenuContentwidget)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.MenuContentverticalLayout_2 = QtWidgets.QVBoxLayout()
        self.MenuContentverticalLayout_2.setObjectName("MenuContentverticalLayout_2")
        self.Menuwidget_2 = QtWidgets.QWidget(self.MenuContentwidget)
        self.Menuwidget_2.setMinimumSize(QtCore.QSize(0, 0))
        self.Menuwidget_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Menuwidget_2.setObjectName("Menuwidget_2")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.Menuwidget_2)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        
        # Home
        self.Homewidget = QtWidgets.QWidget(self.Menuwidget_2)
        self.Homewidget.setAutoFillBackground(False)
        self.Homewidget.setStyleSheet("""
                                          #Homewidget{
                                              color: #d2d3df;
                                              font-weight: bold;
                                              font-size: 15px;
                                              }
                                          
                                          #Homewidget:hover{
                                                  background-color: #1c1c28;
                                              }
                                      """)
        self.Homewidget.setObjectName("Homewidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Homewidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.Homewidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_3.setStyleSheet("""
                                   #pushButton_3{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.pushButton_3.setFixedWidth(50)
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.Homewidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_2.setStyleSheet("""
                                   #pushButton_2{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.Homewidget)
        self.Createwidget = QtWidgets.QWidget(self.Menuwidget_2)
        self.Createwidget.setStyleSheet("""
                                          #Createwidget{
                                              color: #d2d3df;
                                              font-weight: bold;
                                              font-size: 15px;
                                              }
                                          
                                          #Createwidget:hover{
                                                  background-color: #1c1c28;
                                              }
                                      """)
        self.Createwidget.setObjectName("Createwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Createwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.Createwidget)
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_5.setStyleSheet("""
                                   #pushButton_5{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.pushButton_5.setFixedWidth(50)
        self.horizontalLayout_3.addWidget(self.pushButton_5)
        self.pushButton_4 = QtWidgets.QPushButton(self.Createwidget)
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.setStyleSheet("""
                                   #pushButton_4{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.horizontalLayout_3.addWidget(self.pushButton_4)
        self.verticalLayout_3.addWidget(self.Createwidget)
        self.Pipelinewidget = QtWidgets.QWidget(self.Menuwidget_2)
        self.Pipelinewidget.setStyleSheet("""
                                          #Pipelinewidget{
                                              color: #d2d3df;
                                              font-weight: bold;
                                              font-size: 15px;
                                              }
                                          
                                          #Pipelinewidget:hover{
                                                  background-color: #1c1c28;
                                              }
                                      """)
        self.Pipelinewidget.setObjectName("Pipelinewidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.Pipelinewidget)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_6 = QtWidgets.QPushButton(self.Pipelinewidget)
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_6.setStyleSheet("""
                                   #pushButton_6{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.pushButton_6.setFixedWidth(50)
        self.horizontalLayout_4.addWidget(self.pushButton_6)
        self.pushButton_11 = QtWidgets.QPushButton(self.Pipelinewidget)
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_11.setStyleSheet("""
                                   #pushButton_11{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.verticalLayout_3.addWidget(self.Pipelinewidget)
        self.Historywidget_3 = QtWidgets.QWidget(self.Menuwidget_2)
        self.Historywidget_3.setStyleSheet("""
                                          #Historywidget_3{
                                              color: #d2d3df;
                                              font-weight: bold;
                                              font-size: 15px;
                                              }
                                          
                                          #Historywidget_3:hover{
                                                  background-color: #1c1c28;
                                              }
                                      """)
        self.Historywidget_3.setObjectName("Historywidget_3")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.Historywidget_3)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.Historywidget_3)
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_8.setStyleSheet("""
                                   #pushButton_8{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.pushButton_8.setFixedWidth(50)
        self.horizontalLayout_6.addWidget(self.pushButton_8)
        self.pushButton_7 = QtWidgets.QPushButton(self.Historywidget_3)
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_7.setStyleSheet("""
                                   #pushButton_7{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.horizontalLayout_6.addWidget(self.pushButton_7)
        self.verticalLayout_3.addWidget(self.Historywidget_3)
        self.Settingswidget_2 = QtWidgets.QWidget(self.Menuwidget_2)
        self.Settingswidget_2.setStyleSheet("""
                                          #Settingswidget_2{
                                              color: #d2d3df;
                                              font-weight: bold;
                                              font-size: 15px;
                                              }
                                          
                                          #Settingswidget_2:hover{
                                                  background-color: #1c1c28;
                                              }
                                      """)
        self.Settingswidget_2.setObjectName("Settingswidget_2")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.Settingswidget_2)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.pushButton_10 = QtWidgets.QPushButton(self.Settingswidget_2)
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_10.setStyleSheet("""
                                   #pushButton_10{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.pushButton_10.setFixedWidth(50)
        self.horizontalLayout_5.addWidget(self.pushButton_10)
        self.pushButton_9 = QtWidgets.QPushButton(self.Settingswidget_2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_9.setStyleSheet("""
                                   #pushButton_9{
                                        background-color: transparent;
                                        color: #d2d3df;
                                        font-weight: bold;
                                        font-size: 15px;
                                        border: 0px;
                                   }
                                   """)
        self.horizontalLayout_5.addWidget(self.pushButton_9)
        self.verticalLayout_3.addWidget(self.Settingswidget_2)
        self.gridLayout_11.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.MenuContentverticalLayout_2.addWidget(self.Menuwidget_2)
        self.MenuBottomwidget_3 = QtWidgets.QWidget(self.MenuContentwidget)
        self.MenuBottomwidget_3.setObjectName("MenuBottomwidget_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.MenuBottomwidget_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.MenuBottomContentwidget_4 = QtWidgets.QWidget(self.MenuBottomwidget_3)
        self.MenuBottomContentwidget_4.setObjectName("MenuBottomContentwidget_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.MenuBottomContentwidget_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.pushButton_7_exit = QtWidgets.QPushButton(self.MenuBottomContentwidget_4)
        self.pushButton_7_exit.setStyleSheet("color: #676b86;")
        self.pushButton_7_exit.setObjectName("pushButton_7_exit")
        self.gridLayout_10.addWidget(self.pushButton_7_exit, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.MenuBottomContentwidget_4, 0, 0, 1, 1)
        self.MenuContentverticalLayout_2.addWidget(self.MenuBottomwidget_3)
        self.gridLayout_8.addLayout(self.MenuContentverticalLayout_2, 0, 0, 1, 1)
        self.MenuMainverticalLayout.addWidget(self.MenuContentwidget)
        self.gridLayout_7.addLayout(self.MenuMainverticalLayout, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.sideMainwidget, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.SideBarwidget, 0, 0, 1, 1)
        self.stackedWidget = QtWidgets.QStackedWidget(self.MainWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        
        # Home stacked page Widget
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_12.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_12.setSpacing(0)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.Contentwidget = QtWidgets.QWidget(self.page)
        self.Contentwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.Contentwidget.setStyleSheet("background-color: #1c1c28")
        self.Contentwidget.setObjectName("Contentwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.Contentwidget)
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.ContentverticalLayout = QtWidgets.QVBoxLayout()
        self.ContentverticalLayout.setSpacing(0)
        self.ContentverticalLayout.setObjectName("ContentverticalLayout")
        self.Uploaderwidget = QtWidgets.QWidget(self.Contentwidget)
        self.Uploaderwidget.setMinimumSize(QtCore.QSize(0, 60))
        self.Uploaderwidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Uploaderwidget.setStyleSheet("background-color: #2b2e41")
        self.Uploaderwidget.setObjectName("Uploaderwidget")
        self.Uploaderwidget.setStyleSheet("""
                                          QWidget#Uploaderwidget{
                                              background-color: #2b2e41;
                                              border-radius: 5px;
                                              }
                                          """)
        self.gridLayout_4 = QtWidgets.QGridLayout(self.Uploaderwidget)
        self.gridLayout_4.setContentsMargins(25, -1, 25, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.Uploaderwidget)
        self.label.setMaximumSize(QtCore.QSize(40, 16777215))
        self.label.setStyleSheet("""
                                 background-color:#2b2e41;
                                font-weight: bold;
                                font-size: 15px;
                                border-radius: 0px;
                                 """)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.Uploaderwidget)
        self.label_2.setStyleSheet("background-color:#1c1c28;\n"
                                   "color: #676b86;"
                                   "border-radius:10px;"
                                   "padding-left: 10px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.pushButton = QtWidgets.QPushButton(self.Uploaderwidget)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton.setStyleSheet("""
                                           font-weight: bold;
                                           background-color:#2b2e41;
                                           """)
        
        
        self.pushButtonstart = QtWidgets.QPushButton(self.Uploaderwidget)
        self.pushButtonstart.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonstart.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonstart.setObjectName("pushButtonstart")
        self.pushButtonstart.setStyleSheet("""
                                           font-weight: bold;
                                           background-color:#2b2e41;
                                           """)
        self.horizontalLayout.addWidget(self.pushButtonstart)
        
        self.gridLayout_4.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.ContentverticalLayout.addWidget(self.Uploaderwidget)
        self.Progresswidget = QtWidgets.QWidget(self.Contentwidget)
        self.Progresswidget.setMinimumSize(QtCore.QSize(0, 60))
        self.Progresswidget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Progresswidget.setStyleSheet("background-color: #2b2e41")
        self.Progresswidget.setObjectName("Progresswidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Progresswidget)
        self.gridLayout_5.setContentsMargins(9, -1, 9, -1)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.progressBar = QtWidgets.QProgressBar(self.Progresswidget)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 40))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    background-color:#1c1c25;\n"
"    color: #fff;\n"
"    border: 2px solid #41455c;\n"
"    border-radius: 5px;\n"
"    text-align: center;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: #2b2e41;\n"
"}")
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_5.addWidget(self.progressBar, 0, 0, 1, 1)
        self.ContentverticalLayout.addWidget(self.Progresswidget)
        self.Statuswidget = QtWidgets.QWidget(self.Contentwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Statuswidget.sizePolicy().hasHeightForWidth())
        self.Statuswidget.setSizePolicy(sizePolicy)
        self.Statuswidget.setMinimumSize(QtCore.QSize(0, 0))
        self.Statuswidget.setStyleSheet("background-color: #2b2e41")
        self.Statuswidget.setObjectName("Statuswidget")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.Statuswidget)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.textBrowser = QtWidgets.QTextBrowser(self.Statuswidget)
        self.textBrowser.setObjectName("textBrowser")
        self.textBrowser.setStyleSheet("border-radius:10px;"
                                       "background-color:#1c1c25;"
                                       "padding:10px;")
        self.gridLayout_19.addWidget(self.textBrowser, 0, 0, 1, 1)
        self.ContentverticalLayout.addWidget(self.Statuswidget)
        self.gridLayout_3.addLayout(self.ContentverticalLayout, 0, 1, 1, 1)
        self.gridLayout_12.addWidget(self.Contentwidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page)
        
        
        # History Widget
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_13.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_13.setSpacing(0)
        self.gridLayout_13.setObjectName("gridLayout_13")

        self.HistoryWidget = QtWidgets.QWidget(self.page_2)
        self.HistoryWidget.setStyleSheet("background-color: #1c1c28")
        self.HistoryWidget.setObjectName("HistoryWidget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.HistoryWidget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.HistoryHeaderwidget = QtWidgets.QWidget(self.HistoryWidget)
        self.HistoryHeaderwidget.setMinimumSize(QtCore.QSize(0, 60))
        self.HistoryHeaderwidget.setStyleSheet("background-color: #2b2e41")
        self.HistoryHeaderwidget.setObjectName("HistoryHeaderwidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.HistoryHeaderwidget)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.sortBywidget = QtWidgets.QWidget(self.HistoryHeaderwidget)
        self.sortBywidget.setMinimumSize(QtCore.QSize(200, 0))
        self.sortBywidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.sortBywidget.setObjectName("sortBywidget")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.sortBywidget)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.sortComboBox = QtWidgets.QComboBox(self.sortBywidget)
        self.sortComboBox.setObjectName("sortComboBox")
        self.sortComboBox.addItem("")
        self.horizontalLayout_8.addWidget(self.sortComboBox)
        self.sortComboBox.addItem("Date Oldest")
        self.sortComboBox.addItem("Date Latest")
        self.horizontalLayout_7.addWidget(self.sortBywidget)
        self.Searchwidget_2 = QtWidgets.QWidget(self.HistoryHeaderwidget)
        self.Searchwidget_2.setObjectName("Searchwidget_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.Searchwidget_2)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.lineEdit = QtWidgets.QLineEdit(self.Searchwidget_2)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_9.addWidget(self.lineEdit)
        self.horizontalLayout_7.addWidget(self.Searchwidget_2)
        self.gridLayout_14.addWidget(self.HistoryHeaderwidget, 0, 0, 1, 1)
        self.HistoryDisplaywidget = QtWidgets.QWidget(self.HistoryWidget)
        self.HistoryDisplaywidget.setStyleSheet("background-color: #2b2e41")
        self.HistoryDisplaywidget.setObjectName("HistoryDisplaywidget")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.HistoryDisplaywidget)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.HistorylistWidget = QtWidgets.QListWidget(self.HistoryDisplaywidget)
        self.HistorylistWidget.setObjectName("HistorylistWidget")
        self.HistorylistWidget.setSpacing(10)
        self.HistorylistWidget.setStyleSheet("""
                                             QListWidget{
                                                 border: None;
                                                 }
                                             QListWidget::item{
                                                 padding: 0px 10px;
                                                 background-color: #1c1c28;
                                                 border-radius:5px;
                                                }
                                             """)
        self.gridLayout_15.addWidget(self.HistorylistWidget, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.HistoryDisplaywidget, 1, 0, 1, 1)
        self.gridLayout_13.addWidget(self.HistoryWidget, 0, 0, 1, 1)
        
        self.stackedWidget.addWidget(self.page_2)
        
        
        
        
        # Settings Widget
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_16.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_16.setSpacing(0)
        self.gridLayout_16.setObjectName("gridLayout_16")

        self.SettingsWidget = QtWidgets.QWidget(self.page_3)
        self.SettingsWidget.setStyleSheet("background-color: #1c1c28")
        self.SettingsWidget.setObjectName("SettingsWidget")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.SettingsWidget)
        self.gridLayout_17.setObjectName("gridLayout_17")

        
        self.SettingsDisplaywidget = QtWidgets.QWidget(self.SettingsWidget)
        self.SettingsDisplaywidget.setStyleSheet("background-color: #2b2e41")
        self.SettingsDisplaywidget.setObjectName("SettingsDisplaywidget")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.SettingsDisplaywidget)
        self.gridLayout_18.setObjectName("gridLayout_15")
        # enter data inside
        
        self.settingsMenusWidgetUploader = QtWidgets.QWidget(self.SettingsDisplaywidget)
        self.settingsMenusWidgetUploader.setStyleSheet("background-color: #2b2e41")
        self.settingsMenusWidgetUploader.setObjectName("settingsMenusWidgetUploader")
        self.veritcLayout_10 = QtWidgets.QVBoxLayout(self.settingsMenusWidgetUploader)
        self.veritcLayout_10.setObjectName("veritcLayout_10")
        self.gridLayout_18.addWidget(self.settingsMenusWidgetUploader, 0,0,1,1)
        
        self.spaceWidgetSettings = QtWidgets.QWidget(self.SettingsDisplaywidget)
        self.spaceWidgetSettings.setMinimumSize(QtCore.QSize(100, 50))
        self.gridLayout_18.addWidget(self.spaceWidgetSettings, 1,0,1,1)
        
        self.settingsMenusWidgetPublisher = QtWidgets.QWidget(self.SettingsDisplaywidget)
        self.settingsMenusWidgetPublisher.setStyleSheet("background-color: #2b2e41")
        self.settingsMenusWidgetPublisher.setObjectName("settingsMenusWidgetPublisher")
        self.veritcLayout_10Publisher = QtWidgets.QVBoxLayout(self.settingsMenusWidgetPublisher)
        self.veritcLayout_10Publisher.setObjectName("veritcLayout_10Publisher")
        self.gridLayout_18.addWidget(self.settingsMenusWidgetPublisher, 2,0,1,1)


        
           
        
        self.gridLayout_17.addWidget(self.SettingsDisplaywidget, 1, 0, 1, 1)
        self.gridLayout_16.addWidget(self.SettingsWidget, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.page_3)
        
        
        
        
        # Publish stacked page Widget
        self.pagePublish = QtWidgets.QWidget()
        self.pagePublish.setObjectName("pagePublish")
        self.gridLayout_mainPublish = QtWidgets.QGridLayout(self.pagePublish)
        self.gridLayout_mainPublish.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_mainPublish.setSpacing(0)
        self.gridLayout_mainPublish.setObjectName("gridLayout_mainPublish")
        self.ContentwidgetPublish = QtWidgets.QWidget(self.pagePublish)
        self.ContentwidgetPublish.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.ContentwidgetPublish.setStyleSheet("background-color: #1c1c28")
        self.ContentwidgetPublish.setObjectName("ContentwidgetPublish")
        self.gridLayout_contentWidget = QtWidgets.QGridLayout(self.ContentwidgetPublish)
        self.gridLayout_contentWidget.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_contentWidget.setSpacing(6)
        self.gridLayout_contentWidget.setObjectName("gridLayout_contentWidget")
        self.ContentverticalLayoutPublish = QtWidgets.QVBoxLayout()
        self.ContentverticalLayoutPublish.setSpacing(0)
        self.ContentverticalLayoutPublish.setObjectName("ContentverticalLayoutPublish")
        self.Publisherwidget = QtWidgets.QWidget(self.ContentwidgetPublish)
        self.Publisherwidget.setMinimumSize(QtCore.QSize(0, 60))
        self.Publisherwidget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.Publisherwidget.setStyleSheet("background-color: #2b2e41")
        self.Publisherwidget.setObjectName("Publisherwidget")
        self.Publisherwidget.setStyleSheet("""
                                          QWidget#Publisherwidget{
                                              background-color: #2b2e41;
                                              border-radius: 5px;
                                              }
                                          """)
        self.gridLayout_Publisherwidget = QtWidgets.QGridLayout(self.Publisherwidget)
        self.gridLayout_Publisherwidget.setContentsMargins(25, -1, 25, -1)
        self.gridLayout_Publisherwidget.setObjectName("gridLayout_Publisherwidget")
        self.horizontalLayoutPublisher = QtWidgets.QHBoxLayout()
        self.horizontalLayoutPublisher.setObjectName("horizontalLayoutPublisher")
        self.labelPublisher = QtWidgets.QLabel(self.Publisherwidget)
        self.labelPublisher.setMaximumSize(QtCore.QSize(150, 16777215))
        self.labelPublisher.setStyleSheet("""
                                 background-color:#2b2e41;
                                font-weight: bold;
                                font-size: 20px;
                                border-radius: 0px;
                                 """)
        self.labelPublisher.setObjectName("labelPublisher")
        self.horizontalLayoutPublisher.addWidget(self.labelPublisher)
        # self.label_2Publisher = QtWidgets.QLabel(self.Publisherwidget)
        # self.label_2Publisher.setStyleSheet("background-color:#1c1c28;\n"
        #                            "color: #676b86;"
        #                            "border-radius:10px;"
        #                            "padding-left: 10px;")
        # self.label_2Publisher.setObjectName("label_2Publisher")
        # self.horizontalLayoutPublisher.addWidget(self.label_2Publisher)
        # self.pushButtonPublisher = QtWidgets.QPushButton(self.Publisherwidget)
        # self.pushButtonPublisher.setMinimumSize(QtCore.QSize(0, 40))
        # self.pushButtonPublisher.setMaximumSize(QtCore.QSize(120, 16777215))
        # self.pushButtonPublisher.setObjectName("pushButtonPublisher")
        # self.horizontalLayoutPublisher.addWidget(self.pushButtonPublisher)
        # self.pushButtonPublisher.setStyleSheet("""
        #                                    font-weight: bold;
        #                                    background-color:#2b2e41;
        #                                    """)
        
        self.spacerpublish = QtWidgets.QSpacerItem(20,20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayoutPublisher.addItem(self.spacerpublish)
        
        # self.planSelectorWidget = QtWidgets.QComboBox(self.Publisherwidget)
        # self.planSelectorWidget.setMinimumSize(QtCore.QSize(0, 40))
        # self.planSelectorWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        # self.planSelectorWidget.setStyleSheet("""
        #                                    font-weight: bold;
        #                                    background-color:#2b2e41;
        #                                    """)
        # self.planSelectorWidget.addItem("Select Test Plan")
        # self.horizontalLayoutPublisher.addWidget(self.planSelectorWidget)
  
        
        self.pushButtonstartPublisher = QtWidgets.QPushButton(self.Publisherwidget)
        self.pushButtonstartPublisher.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonstartPublisher.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonstartPublisher.setObjectName("pushButtonstartPublisher")
        self.pushButtonstartPublisher.setStyleSheet("""
                                           font-weight: bold;
                                           background-color:#2b2e41;
                                           """)
        self.horizontalLayoutPublisher.addWidget(self.pushButtonstartPublisher)
        
        self.pushButtonstopPublisher = QtWidgets.QPushButton(self.Publisherwidget)
        self.pushButtonstopPublisher.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButtonstopPublisher.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButtonstopPublisher.setObjectName("pushButtonstopPublisher")
        self.pushButtonstopPublisher.setStyleSheet("""
                                           font-weight: bold;
                                           background-color:#2b2e41;
                                           """)
        self.horizontalLayoutPublisher.addWidget(self.pushButtonstopPublisher)
        
        self.gridLayout_Publisherwidget.addLayout(self.horizontalLayoutPublisher, 0, 0, 1, 1)
        self.ContentverticalLayoutPublish.addWidget(self.Publisherwidget)
        self.Progresswidget_publisher = QtWidgets.QWidget(self.Contentwidget)
        self.Progresswidget_publisher.setMinimumSize(QtCore.QSize(0, 60))
        self.Progresswidget_publisher.setMaximumSize(QtCore.QSize(16777215, 60))
        self.Progresswidget_publisher.setStyleSheet("background-color: #2b2e41")
        self.Progresswidget_publisher.setObjectName("Progresswidget_publisher")

        self.gridLayout_Progresswidget_publisher = QtWidgets.QGridLayout(self.Progresswidget_publisher)
        self.gridLayout_Progresswidget_publisher.setContentsMargins(9, -1, 9, -1)
        self.gridLayout_Progresswidget_publisher.setObjectName("gridLayout_Progresswidget_publisher")
        # self.progressBar_publisher = QtWidgets.QProgressBar(self.Progresswidget_publisher)
        # self.progressBar_publisher.setMinimumSize(QtCore.QSize(0, 40))
        # self.progressBar_publisher.setStyleSheet("QProgressBar {\n"
        #                                         "    background-color:#1c1c25;\n"
        #                                         "    color: #fff;\n"
        #                                         "    border: 2px solid #41455c;\n"
        #                                         "    border-radius: 5px;\n"
        #                                         "    text-align: center;\n"
        #                                         "}\n"
        #                                         "\n"
        #                                         "QProgressBar::chunk {\n"
        #                                         "    background-color: #2b2e41;\n"
        #                                         "}")
        # self.progressBar_publisher.setProperty("value", 24)
        # self.progressBar_publisher.setObjectName("progressBar_publisher")
        # self.gridLayout_Progresswidget_publisher.addWidget(self.progressBar_publisher, 0, 0, 1, 1)
        # self.progressBar_publisher.setValue(0)
        self.TotalPublishedLabel = QtWidgets.QLabel(self.Progresswidget_publisher)
        self.TotalPublishedLabel.setMinimumSize(QtCore.QSize(0, 40))
        self.TotalPublishedLabel.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TotalPublishedLabel.setObjectName("TotalPublishedLabel")
        self.TotalPublishedLabel.setStyleSheet("""
                                           color: #d2d3df;
                                           font-weight: bold;
                                           font-size: 15px;
                                           padding-left: 15px;
                                           """)
        self.TotalPublishedLabel.setText(f"TOTAL TEST SUITES PUBLISHED: 0")
        self.gridLayout_Progresswidget_publisher.addWidget(self.TotalPublishedLabel, 0, 0, 1, 1)

        self.ContentverticalLayoutPublish.addWidget(self.Progresswidget_publisher)
        self.StatuswidgetPublisher = QtWidgets.QWidget(self.ContentwidgetPublish)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.StatuswidgetPublisher.sizePolicy().hasHeightForWidth())
        self.StatuswidgetPublisher.setSizePolicy(sizePolicy)
        self.StatuswidgetPublisher.setMinimumSize(QtCore.QSize(0, 0))
        self.StatuswidgetPublisher.setStyleSheet("background-color: #2b2e41")
        # 1c1c25 2b2e41
        self.StatuswidgetPublisher.setObjectName("StatuswidgetPublisher")
        self.gridLayout_StatuswidgetPublisher = QtWidgets.QGridLayout(self.StatuswidgetPublisher)
        self.gridLayout_StatuswidgetPublisher.setObjectName("gridLayout_StatuswidgetPublisher")
        # self.listWidgetPublisher = QtWidgets.QListWidget(self.StatuswidgetPublisher)
        # self.listWidgetPublisher.setObjectName("listWidgetPublisher")
        # self.listWidgetPublisher.setStyleSheet("border-radius:10px;"
        #                                 "background-color:#1c1c25;"
        #                                 "padding:10px;")
        # self.gridLayout_StatuswidgetPublisher.addWidget(self.listWidgetPublisher, 0, 0, 1, 1)
        self.textBrowserPublisher = QtWidgets.QTextBrowser(self.StatuswidgetPublisher)
        self.textBrowserPublisher.setObjectName("textBrowserPublisher")
        self.textBrowserPublisher.setStyleSheet("border-radius:10px;"
                                       "background-color:#1c1c25;"
                                       "padding:10px;")
        self.gridLayout_StatuswidgetPublisher.addWidget(self.textBrowserPublisher, 0, 0, 1, 1)
        self.ContentverticalLayoutPublish.addWidget(self.StatuswidgetPublisher)
        self.gridLayout_contentWidget.addLayout(self.ContentverticalLayoutPublish, 0, 1, 1, 1)
        self.gridLayout_mainPublish.addWidget(self.ContentwidgetPublish, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pagePublish)
        
        
        
        
        # History Widget detail viewer Window
        self.pageHistoryViewer = QtWidgets.QWidget()
        self.pageHistoryViewer.setObjectName("pageHistoryViewer")
        self.gridLayoutHistoryViewer = QtWidgets.QGridLayout(self.pageHistoryViewer)
        self.gridLayoutHistoryViewer.setContentsMargins(0, 0, 0, 0)
        self.gridLayoutHistoryViewer.setSpacing(0)
        self.gridLayoutHistoryViewer.setObjectName("gridLayoutHistoryViewer")

        self.HistoryViewerWidget = QtWidgets.QWidget(self.pageHistoryViewer)
        self.HistoryViewerWidget.setStyleSheet("background-color: #1c1c28")
        self.HistoryViewerWidget.setObjectName("HistoryViewerWidget")
        self.gridLayoutHistoryVW = QtWidgets.QGridLayout(self.HistoryViewerWidget)
        self.gridLayoutHistoryVW.setObjectName("gridLayoutHistoryVW")
        self.HistoryViewerHeaderwidget = QtWidgets.QWidget(self.HistoryViewerWidget)
        self.HistoryViewerHeaderwidget.setMinimumSize(QtCore.QSize(0, 60))
        self.HistoryViewerHeaderwidget.setStyleSheet("background-color: #2b2e41")
        self.HistoryViewerHeaderwidget.setObjectName("HistoryViewerHeaderwidget")
        self.VerticalLayoutHVHW = QtWidgets.QVBoxLayout(self.HistoryViewerHeaderwidget)
        self.VerticalLayoutHVHW.setObjectName("VerticalLayoutHVHW")
        
        
        self.TopHeaderWidget = QtWidgets.QWidget(self.HistoryViewerHeaderwidget)
        self.TopHeaderWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.TopHeaderWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.TopHeaderWidget.setObjectName("TopHeaderWidget")
        self.horizontalLayout_TopHeaderWidget = QtWidgets.QHBoxLayout(self.TopHeaderWidget)
        self.horizontalLayout_TopHeaderWidget.setObjectName("horizontalLayout_TopHeaderWidget")
       
        self.pushButtonBackHV = QtWidgets.QPushButton(self.HistoryViewerHeaderwidget)
        self.pushButtonBackHV.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButtonBackHV.setMaximumSize(QtCore.QSize(30, 16777215))
        self.pushButtonBackHV.setObjectName("pushButtonBackHV")
        self.pushButtonBackHV.setStyleSheet("""
                                            background-color: transparent;
                                            color: #d2d3df;
                                            font-weight: bold;
                                            border: 0px;
                                            """)
        self.horizontalLayout_TopHeaderWidget.addWidget(self.pushButtonBackHV)
        
        self.labelTitleHV = QtWidgets.QLabel(self.HistoryViewerHeaderwidget)
        self.labelTitleHV.setMinimumSize(QtCore.QSize(0, 40))
        self.labelTitleHV.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelTitleHV.setObjectName("pushButtonBackHV")
        self.labelTitleHV.setStyleSheet("""
                                            font-size: 20px;
                                            font-weight: bold;
                                            """)
        self.labelTitleHV.setAlignment(Qt.AlignCenter)
        self.horizontalLayout_TopHeaderWidget.addWidget(self.labelTitleHV)
        self.VerticalLayoutHVHW.addWidget(self.TopHeaderWidget)
        
        
        self.BottomHeaderWidget = QtWidgets.QWidget(self.HistoryViewerHeaderwidget)
        self.BottomHeaderWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.BottomHeaderWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.BottomHeaderWidget.setObjectName("BottomHeaderWidget")
        self.horizontalLayout_BottomHeaderWidget = QtWidgets.QHBoxLayout(self.BottomHeaderWidget)
        self.horizontalLayout_BottomHeaderWidget.setObjectName("horizontalLayout_BottomHeaderWidget")
        
        
        # DATE
        self.labelDate = QtWidgets.QLabel(self.HistoryViewerHeaderwidget)
        self.labelDate.setMinimumSize(QtCore.QSize(0, 40))
        self.labelDate.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelDate.setObjectName("labelDate")
        self.labelDate.setStyleSheet("""
                                            font-weight: bold;
                                            """)
        self.horizontalLayout_BottomHeaderWidget.addWidget(self.labelDate)
        self.labelDate.setText("DATE: ")
        
        self.labelDateValue = QtWidgets.QLabel(self.HistoryViewerHeaderwidget)
        self.labelDateValue.setMinimumSize(QtCore.QSize(0, 40))
        self.labelDateValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelDateValue.setObjectName("labelDateValue")
        self.labelDateValue.setStyleSheet("""
                                            font-weight: bold;
                                            """)
        self.horizontalLayout_BottomHeaderWidget.addWidget(self.labelDateValue)
        self.spacerItem1 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_BottomHeaderWidget.addItem(self.spacerItem1)
        
       # Time
        self.labelTime = QtWidgets.QLabel(self.HistoryViewerHeaderwidget)
        self.labelTime.setMinimumSize(QtCore.QSize(0, 40))
        self.labelTime.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelTime.setObjectName("labelTime")
        self.labelTime.setStyleSheet("""
                                        font-weight: bold;
                                        """)
        self.horizontalLayout_BottomHeaderWidget.addWidget(self.labelTime)
        self.labelTime.setText("TIME: ")
        
        self.labelTimeValue = QtWidgets.QLabel(self.HistoryViewerHeaderwidget)
        self.labelTimeValue.setMinimumSize(QtCore.QSize(0, 40))
        self.labelTimeValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelTimeValue.setObjectName("labelTimeValue")
        self.labelTimeValue.setStyleSheet("""
                                            font-weight: bold;
                                         """)
        self.horizontalLayout_BottomHeaderWidget.addWidget(self.labelTimeValue)
        self.spacerItem2 = QtWidgets.QSpacerItem(20, 5, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_BottomHeaderWidget.addItem(self.spacerItem2)
        

        # Progress
        self.labelProgress = QtWidgets.QLabel(self.HistoryViewerHeaderwidget)
        self.labelProgress.setMinimumSize(QtCore.QSize(0, 40))
        self.labelProgress.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelProgress.setObjectName("labelProgress")
        self.labelProgress.setStyleSheet("""
                                            font-weight: bold;
                                            """)
        self.horizontalLayout_BottomHeaderWidget.addWidget(self.labelProgress)
        self.labelProgress.setText("PROGRESS : ")
        self.labelProgressValue = QtWidgets.QLabel(self.HistoryViewerHeaderwidget)
        self.labelProgressValue.setMinimumSize(QtCore.QSize(0, 40))
        self.labelProgressValue.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.labelProgressValue.setObjectName("labelProgressValue")
        self.labelProgressValue.setStyleSheet("""
                                            font-weight: bold;
                                            """)
        self.horizontalLayout_BottomHeaderWidget.addWidget(self.labelProgressValue)
        
        
        self.VerticalLayoutHVHW.addWidget(self.BottomHeaderWidget)
        self.gridLayoutHistoryVW.addWidget(self.HistoryViewerHeaderwidget, 0, 0, 1, 1)
        
        self.HistoryViewerDisplaywidget = QtWidgets.QWidget(self.HistoryViewerWidget)
        self.HistoryViewerDisplaywidget.setStyleSheet("background-color: #2b2e41")
        self.HistoryViewerDisplaywidget.setObjectName("HistoryViewerDisplaywidget")
        self.gridLayoutHVDW = QtWidgets.QGridLayout(self.HistoryViewerDisplaywidget)
        self.gridLayoutHVDW.setObjectName("gridLayoutHVDW")
        self.HistoryDetailsTextBrowser = QtWidgets.QTextBrowser(self.HistoryViewerDisplaywidget)
        self.HistoryDetailsTextBrowser.setObjectName("HistoryDetailsTextBrowser")
        self.HistoryDetailsTextBrowser.setStyleSheet("""
                                                  padding: 10px 10px;
                                                  border: 0px;
                                                  background-color: #1c1c28;
                                                  color: #ffffff;
                                                
                                              """)
        self.gridLayoutHVDW.addWidget(self.HistoryDetailsTextBrowser, 0, 0, 1, 1)
        self.gridLayoutHistoryVW.addWidget(self.HistoryViewerDisplaywidget, 1, 0, 1, 1)
        self.gridLayoutHistoryViewer.addWidget(self.HistoryViewerWidget, 0, 0, 1, 1)
        
        self.stackedWidget.addWidget(self.pageHistoryViewer)
        
        
        
        
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.MainWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 898, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Titlelabel_3.setText(_translate("MainWindow", "QM Uploader"))

        self.pushButton_2.setText(_translate("MainWindow", "Home"))
        self.pushButton_4.setText(_translate("MainWindow", "Publish"))
        self.pushButton_11.setText(_translate("MainWindow", "Pipeline"))
        self.pushButton_7.setText(_translate("MainWindow", "History"))
        self.pushButton_9.setText(_translate("MainWindow", "Settings"))
        self.pushButton_7_exit.setText(_translate("MainWindow", "Exit"))
        self.label.setText(_translate("MainWindow", "File"))
        self.label_2.setText(_translate("MainWindow", "Your selected file ........."))
        self.pushButtonstart.setText(_translate("MainWindow", "Start"))
        self.pushButton.setText(_translate("MainWindow", "Open"))
        
        self.labelPublisher.setText(_translate("MainWindow", "Publisher"))
        # self.label_2Publisher.setText(_translate("MainWindow", "Your selected file ........."))
        self.pushButtonstartPublisher.setText(_translate("MainWindow", "Start"))
        self.pushButtonstopPublisher.setText(_translate("MainWindow", "Stop"))
        # self.pushButtonPublisher.setText(_translate("MainWindow", "Open"))
        
        
        self.sortComboBox.setItemText(0, _translate("MainWindow", "Sort Items by...."))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search the History"))

    
        
